name: Build and test

on:
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Type check
      run: pnpm type-check

    - name: Lint
      run: pnpm lint

    - name: Test
      run: pnpm test

    - name: Build
      run: pnpm build

    - name: Type check examples
      run: pnpm examples:type-check
      
